### ISSUE TITLE
[SOL-43240] The queue name ended with the group name

### ISSUE THREAD

**Issue by liuz7** [SolaceProducts/solace-spring-cloud#28]
When i add consumer group in configuration, the queue name is always generated with destination name and group name. But our queue name is predefined. We do not need to append the group name. The code for generation of queue name is found below: 

	private static String getQueueName(String topicName, String groupName,
								SolaceCommonProperties properties,
								boolean isAnonymous, String anonGroupPostfix) {
		String queueName;
		if (isAnonymous) {
			queueName = topicName + QUEUE_NAME_DELIM + JCSMPFactory.onlyInstance().createUniqueName(anonGroupPostfix);
		} else {
			queueName = topicName + QUEUE_NAME_DELIM + groupName;
		}

		return properties.getPrefix() + queueName;
	}

please provide a way to specific a queue name without any group name.

**Comment by Mrc0113** [comment]
Hi @liuz7, 

You're correct, the binder dynamically creates (or expects if you turn auto provisioning off) a queue name that includes the consumer group name on the end. The cloud stream binder follows this naming convention as its' a recommended best practice for a queue in solace to be associated with the consumer/group which consumes from it and this naming format makes that easier. 

Does your organization already have a well defined naming convention that you're required to follow? If so, I'm curious if that naming convention includes the consumer group?

**Comment by liuz7** [comment]
> Hi @liuz7,
> 
> You're correct, the binder dynamically creates (or expects if you turn auto provisioning off) a queue name that includes the consumer group name on the end. The cloud stream binder follows this naming convention as it's a recommended best practice for a queue in solace to be associated with the consumer/group which consumes from it and this naming format makes that easy to identify.
> 
> Does your organization already have a well defined naming convention that you're required to follow? If so, I'm curious if that naming convention includes the consumer group?

We have a pre-defined queue name which does not need to include the group name, would you provide the way for us to use the pre defined queue name?

**Comment by Nephery** [comment]
So if I'm understanding this right, the ask here is to allow the ability to have anonymous consumer groups with durable queues and non-random names.

If so, then I think we should provide two new consumer config options for this:

| Config Option | Default Value | Description |
| --- | --- | --- |
| anonymousGroupDurability | false | Whether to provision a durable queue for the anonymous group. Note that when this is set to `true`, then all durable-queue-related config options will also apply to this binding (e.g. `provisionDurableQueue`). |
| generateUniqueAnonymousGroupName | true | Whether to generate a unique name for the anonymous group. Be aware that if this and `anonymousGroupDurability` are both set to `false`, then your application may throw errors if it encounters any naming collisions. |

And then, we would need to add support for `anonymousGroupPostfix` to be set to `""` (i.e. unset it).

With these changes, you should then be able do your use case by:
1. Setting `generateUniqueAnonymousGroupName` to `false`
1. Setting `anonymousGroupPostfix` to `""`
1. Setting `anonymousGroupDurability` to `true`

Referencing @liuz7 's code snippet, applying the first two settings will basically make it so that `queueName = topicName`. And the last setting will make this queue durable instead of temporary.

**Comment by Nephery** [comment]
Ignore my previous comment.

After discussing with @Mrc0113 , we should just introduce a single consumer config option:
|Config Option|Default Value|Description|
|-|-|-|
|useGroupNameInQueueName|true|Whether or not to use the group name when computing the queue name. If set to `false`, all consumers of the same `destination` which have have this set to `false` will share the same queue regardless of the configured `group` name.|

@Mrc0113 Do we want to introduce another config option to do the same for the error queue?

**Comment by Mrc0113** [comment]
@Nephery Sure, for consistency we should probably have the toggle available on the error queue as well. `true` as default of course

**Comment by Mrc0113** [comment]
@Nephery let's update the description to include what changes in the queue name expected as so: 
> Whether or not to include the group name in the queue name. If set to `true` the queue name is expected to be {PREFIX}{DESTINATION}.{GROUP}. If set to `false`, the queue name is expected to be {PREFIX}{DESTINATION}.
Note that if set to `false` all consumers of the same destination which also have this set to false will consume from the same queue regardless of the configured group name.

**Comment by Nephery** [comment]
Alright, here's the update set of new consumer config options:

|Config Option|Default Value|Description|
|-|-|-|
|useGroupNameInQueueName|true|Whether or not to include the group name in the queue name. If set to `true`, the queue name is expected to be `{PREFIX}{DESTINATION}.{GROUP}`. If set to `false`, the queue name is expected to be `{PREFIX}{DESTINATION}`. <br/>Note that if set to `false`, all consumers of the same `destination` which also have this set to `false` will consume from the same queue regardless of the configured `group` name.|
|useGroupNameInErrorQueueName|true|Whether or not to include the group name in the error queue name. If set to `true`, the error queue name is expected to be `{PREFIX}{DESTINATION}.{GROUP}.error`. If set to `false`, the error queue name is expected to be `{PREFIX}{DESTINATION}.error`. <br/>Note that if set to `false`, all consumers of the same `destination` which also have this set to `false` will republish failed messages to the same error queue regardless of the configured `group` name.|

**Comment by Nephery** [comment]
Closed with #75
