### ISSUE TITLE
[SOL-45010] SCSt. Binder Consumer Handling of Messages w/ null payloads is not ideal

### ISSUE THREAD

**Issue by Mrc0113** [SolaceProducts/solace-spring-cloud#54]
SCSt. Binder Consumer Handling of Messages w/ "null" payloads is not ideal. 

When a message with a null payload is received the binder doesn't gracefully handle it. 
If using Spring Cloud Function to implement your code the message is just discarded and the app continues listening for the next message. If using the effectively deprecated annotation, `@StreamListener`, the solace flow is actually shutdown and no more messages are received. Neither of these cases are ideal. If the binder isn't able to create a Spring Message (which doesn't allow a null payload) then at a minimum logging should occur. We should investigate if there are other actions that should be taken.

**Comment by Nephery** [comment]
The crashing is now a non-issue in the 2.0.0 staging branch. But while the new version does fix the crashing, the error still isn't handled properly since the failed message just gets discarded (happens both for `@StreamListener` and Spring Cloud function).

In particular, this fails because [the SolaceErrorMessageHandler depends on having the failed Spring Message](https://github.com/SolaceProducts/solace-spring-cloud/blob/stage-2.0.0/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/util/SolaceErrorMessageHandler.java#L43). The only reason the `SolaceErrorMessageHandler` depends on the failed message is to get the `AcknowledgmentCallback` object. But since the consumer constructs the `AcknowledgmentCallback` before the Spring `Message`, we can actually remove this dependency.

That is, we need to [add another header to the ErrorMessage](https://github.com/SolaceProducts/solace-spring-cloud/blob/stage-2.0.0/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/util/SolaceMessageHeaderErrorMessageStrategy.java) to contain the `AcknowledgmentCallback` object. What I'm not sure about, is what that header should be named. Is it OK to just use the regular `acknowledgmentCallback` header or do we need to create a new header for this (maybe `solace_scst_error_acknowledgentCallback`)?

As an aside, we should also rename the `solace_raw_message` to something like `solace_scst_error_rawMessage`. These `ErrorMessage` headers were overlooked when we redesigned the Spring message headers. I'm thinking of refactoring them to have the prefix `solace_scst_error_`. @Mrc0113 thoughts on this?

**Comment by Nephery** [comment]
Digging down a bit further, I've also found out that the error queue republishing also fails when the inbound SMF message has no payload. This fails because we map the JCSMP message to a Spring message and back to a JCSMP message. We did this to emulate a JCSMP message copy so that we can republish it to the error queue. But to be frank, this was a pretty lazy way to implement this. Instead, we should really be copying the payload, all [SolaceBinderHeaders](https://github.com/SolaceProducts/solace-spring-cloud/blob/stage-2.0.0/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/messaging/SolaceBinderHeaders.java). and all **read-writeable** [SolaceHeaders](https://github.com/SolaceProducts/solace-spring-cloud/blob/stage-2.0.0/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/messaging/SolaceHeaders.java) directly to a new JCSMP message.

**Comment by Nephery** [comment]
> As an aside, we should also rename the solace_raw_message ErrorMessage header to something like solace_scst_error_rawMessage.

Actually, looking at it again, we don't actually use the `solace_raw_message` header for anything. So unless you think someone is going to use this in their error message handler, I think we should remove this.

**Comment by Nephery** [comment]
Discussed @Mrc0113 :
Re-use Spring's `acknowledgmentCallback` header for the `ErrorMessage`.
Keep `solace_raw_message`, but rename it to `solace_scst_rawMessage`.

**Comment by Nephery** [comment]
> 
> 
> Instead, we should really be copying the payload, all [SolaceBinderHeaders](https://github.com/SolaceProducts/solace-spring-cloud/blob/stage-2.0.0/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/messaging/SolaceBinderHeaders.java). and all **read-writeable** [SolaceHeaders](https://github.com/SolaceProducts/solace-spring-cloud/blob/stage-2.0.0/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder-core/src/main/java/com/solace/spring/cloud/stream/binder/messaging/SolaceHeaders.java) directly to a new JCSMP message.

Actually [JCSMP already supports message cloning](https://docs.solace.com/API-Developer-Online-Ref-Documentation/java/com/solacesystems/jcsmp/JCSMPFactory.html#createMessage-com.solacesystems.jcsmp.BytesXMLMessage-), we should use that instead of manually copying everything.

**Comment by Nephery** [comment]
Looks like there's already a `sourceData` header defined in Spring. Not sure why the amqp binder defines their own `amqp_raw_message` header when the `sourceData` header exists. But we should be using that instead of creating our own `solace_scst_rawMessage` header.

**Comment by Mrc0113** [comment]
@Nephery maybe the rabbit binder does it for legacy reasons. It seems like they also set it in the `sourceData` header

**Comment by Nephery** [comment]
Looks like it. Looking at commit https://github.com/spring-projects/spring-integration/commit/78a0ec74e724b23e28326a8a0de3bfd08b179a86 and its parent commit, the `sourceData` header was added somewhat-recently (mid-2019).

**Comment by Nephery** [comment]
Closed with #75
